### ISSUE TITLE
Incorrect vectorization example on page 19 of lecture notes

### ISSUE THREAD

**Issue by rinevard** [mitmath/matrixcalc#7]
I've noticed a small error in the [lecture notes](https://www.dropbox.com/scl/fi/wmo5g2lfb599hwsulnees/Matrix-Calculus.pdf?rlkey=n9xll4xlref9n6lrr3zsmiv12), specifically on page 19 under Definition 20. The example for matrix vectorization appears to be incorrect. By the definition above, we have:

$$
\text{vec}\left(\begin{bmatrix}
1 & 2 \\
3 & 4
\end{bmatrix}\right) = 
\begin{bmatrix}
1 \\
3 \\
2 \\
4
\end{bmatrix}
$$

Here is a screenshot of the course note:
![image](https://github.com/user-attachments/assets/8c779d45-bde5-4666-9dce-3617bea0cf28)

**Comment by stevengj** [comment]
Thanks, I believe this is already fixed in the latest version of the course notes:  https://www.dropbox.com/scl/fi/iq4plt8oqja845cuuosa4/Matrix-Calculus-latest.pdf?rlkey=nsnytdu28jje41nhh1bl2dbba&st=i6lfha0r&dl=0

I'll update the link
